CMS_HOST: "studio.your-domain.com"
CMS_OAUTH2_SECRET: 'REPLACE_WITH_YOUR'
CONTACT_EMAIL: 'REPLACE_WITH_YOUR'
ENABLE_HTTPS: false
ID: 'REPLACE_WITH_YOUR'
JWT_RSA_PRIVATE_KEY:'REPLACE_WITH_YOUR'
LANGUAGE_CODE: en
LMS_HOST: "your-domain.com"
MEILISEARCH_API_KEY: 'REPLACE_WITH_YOUR'
MEILISEARCH_API_KEY_UID: 'REPLACE_WITH_YOUR'
MEILISEARCH_MASTER_KEY: 'REPLACE_WITH_YOUR'
MYSQL_ROOT_PASSWORD: 'REPLACE_WITH_YOUR'
OPENEDX_MYSQL_PASSWORD: 'REPLACE_WITH_YOUR'
OPENEDX_SECRET_KEY: 'REPLACE_WITH_YOUR'
PLATFORM_NAME: 'REPLACE_WITH_YOUR'
PLUGINS:
- custom-authn-mfe
- indigo
- mfe
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
SHARP_IGNORE_GLOBAL_LIBVIPS: 1
